name: ecommerce
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  firebase_core: ^1.0.1
  firebase_database: ^6.1.0
  firebase_storage: ^8.0.3
  provider: ^5.0.0
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0  
  firebase_messaging: ^10.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
